# Generated by Django 3.1.1 on 2021-06-21 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question_Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=250)),
                ('questions', models.CharField(max_length=250)),
                ('answers', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('img', models.ImageField(upload_to='test/')),
            ],
            options={
                'db_table': 'question_answers',
            },
        ),
        migrations.CreateModel(
            name='Question_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='tests/')),
                ('duration', models.FloatField()),
                ('min_grade', models.FloatField()),
            ],
            options={
                'db_table': 'question_groups',
            },
        ),
        migrations.CreateModel(
            name='Question_Group_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.question')),
                ('question_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.question_group')),
            ],
            options={
                'db_table': 'question_group_details',
            },
        ),
        migrations.CreateModel(
            name='Student_and_Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField()),
                ('status', models.BooleanField()),
                ('question_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.question_group')),
            ],
            options={
                'db_table': 'students_and_tests',
            },
        ),
        migrations.CreateModel(
            name='Student_Test_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check', models.BooleanField()),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.answer')),
                ('question_group_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.question_group_detail')),
                ('student_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.student_and_test')),
            ],
        ),
    ]
