# Generated by Django 3.1.1 on 2021-06-21 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_question_answer_question_group_question_group_detail_student_and_test_student_test_details'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student_test_details',
            table='student_test_details',
        ),
    ]
