# Generated by Django 3.1.1 on 2021-06-21 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('additional', '0002_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='region',
            field=models.ForeignKey(db_column='region_code', on_delete=django.db.models.deletion.CASCADE, to='additional.region'),
        ),
    ]
