# Generated by Django 3.1.1 on 2021-06-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional', '0004_blog_contact_lang_news_payment_translate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher_Educenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
